controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_index:
    path: /
    controller: App\Controller\IndexController::index

app_category:
    path: /category
    controller: App\Controller\CategoryController::category

app_user_info:
    path: /user
    controller: App\Controller\UserController::index

app_orders:
    path: /app_orders
    controller: App\Controller\OrdersController::listOrders

app_verify_email:
    path: '/verify/email'
    controller: 'App\Controller\RegistrationController::verifyUserEmail'