controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_category:
    path: /category
    controller: App\Controller\CategoryController::category
    methods: ['GET']